In [1]:
import numpy as np

In [3]:
print (np.__version__)

1.19.2


In [4]:
print (np.__config__)

<module 'numpy.__config__' from 'C:\\Users\\aleja\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


In [16]:
a = (np.random.randn(2, 3, 5,)*10).round(1)

In [17]:
print (a)

[[[ -0.3  -1.3  -2.2  11.   -5.3]
  [ 12.2  -3.4  14.8   3.3  -7.4]
  [ -5.2   7.    8.8  -5.2  17.9]]

 [[  6.7  22.6  18.1  -8.    2.1]
  [ -4.5   6.   -6.4  -5.4   1.2]
  [-18.6   7.3  -3.7 -11.5   7.7]]]


In [57]:
b = np.random.randint(low= 0, high = 10, size=(2, 3, 5))

In [145]:
print (b)

[[[ 0  1  1  6  0]
  [33  0 33  2  0]
  [ 6  2  4  0  1]]

 [[ 5 33 33  4  0]
  [33  1  2 33  0]
  [33 33  1  1  1]]]


In [156]:
c = [x for lista_doble in b for lista in lista_doble for x in lista]

In [ ]:
for element in c:

In [151]:
print

[0, 1, 1, 6, 0, 33, 0, 33, 2, 0, 6, 2, 4, 0, 1, 5, 33, 33, 4, 0, 33, 1, 2, 33, 0, 33, 33, 1, 1, 1]


In [154]:
aux = np.reshape(c, newshape = (2, 3, 5), order='C')

In [155]:
print (aux)

[[[ 0  1  1  6  0]
  [33  0 33  2  0]
  [ 6  2  4  0  1]]

 [[ 5 33 33  4  0]
  [33  1  2 33  0]
  [33 33  1  1  1]]]


In [142]:
c =b.astype(str)

In [143]:
c[0][2][0] = 'A'

In [144]:
print(c)

[[['0' '1' '1' '6' '0']
  ['33' '0' '33' '2' '0']
  ['A' '2' '4' '0' '1']]

 [['5' '33' '33' '4' '0']
  ['33' '1' '2' '33' '0']
  ['33' '33' '1' '1' '1']]]


In [125]:
print (b)

[[[ 0  1  1  6  0]
  [33  0 33  2  0]
  [ 6  2  4  0  1]]

 [[ 5 33 33  4  0]
  [33  1  2 33  0]
  [33 33  1  1  1]]]


In [130]:
b.astype(str)

array([[['0', '1', '1', '6', '0'],
        ['33', '0', '33', '2', '0'],
        ['6', '2', '4', '0', '1']],

       [['5', '33', '33', '4', '0'],
        ['33', '1', '2', '33', '0'],
        ['33', '33', '1', '1', '1']]], dtype='<U11')

In [95]:
f = np.empty((2, 3, 5))

In [96]:
f.shape

(2, 3, 5)

In [105]:
f = (b < 9) & (b > 1)

In [117]:
print (f)

[[[False False False  True False]
  [ True False  True  True False]
  [ True  True  True False False]]

 [[ True False False  True False]
  [ True False  True  True False]
  [ True False False False False]]]


In [120]:
f[f ] = 50

In [121]:
print (f)

[[[False False False  True False]
  [ True False  True  True False]
  [ True  True  True False False]]

 [[ True False False  True False]
  [ True False  True  True False]
  [ True False False False False]]]


[50]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.int8) 
b = a[a > 4]                                                               
print(b)

# [5 6 7 8]


Qs = 1 if a < b else 1.4 * a if a < b < c else 0.69 * b

In [59]:
print (np.mean(b))

3.433333333333333


In [43]:
c = (np.random.rand(2, 3, 5)).round(1)

In [50]:
print (c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [46]:
(np.transpose(c, axes = (2,1,0))).shape

(5, 3, 2)

In [26]:
b = np.ones((5, 2, 3))

In [27]:
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [28]:
b.shape

(5, 2, 3)

In [29]:
a.shape == b.shape

False

In [47]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [48]:
np.transpose(b).shape

(3, 2, 5)

In [ ]:
np.multiply()